@startjson
{
  "size": "размер сообщения, <i>3 байт</i>",
  "spec": [
    {
      "type": "INVITE (0x00), <i>1 байт</i>",
      "conf_id": "ID конференции, <i>4 байт</i>",
	    "part_id": "ID участника, <i>4 байт</i>",
	    "conf_start_ts": "временная метка, <i>8 байт</i>",
    	"part_name": "имя участника, <i>(size-20) байт</i>"
    },
    {
      "type": "INVITE_ACCEPT (0x01), <i>1 байт</i>",
      "id": "ID участника, <i>4 байт</i>",
	    "ep": "Адрес подключения, <i>32 байт</i>",
  	  "name": "имя участника, <i>(size-40) байт</i>"
    },
    {
      "type": "INVITE_REJECT (0x02), <i>1 байт</i>"
    },
    {
      "type": "REENTER (0x03), <i>1 байт</i>",
      "conf_id": "ID конференции, <i>4 байт</i>",
	    "part_id": "ID участника, <i>4 байт</i>"
    },
    {
      "type": "PART_PRESENCE (0х04), <i>1 байт</i>",
      "count": "количество участников, <i>1 байт</i>",
      "states": {
        "id": "ID участника, <i>4 байт</i>",
        "role": "роль участника, <i>1 байт</i>",
        "ep": "Адрес подключения, <i>32 байт</i>",
        "state": "PART_JOIN (0x00) или",
        "": "PART_LEAVE (0x01)"
      }
    },
    {
      "type": "AUDIO (0x05), <i>1 байт</i>",
	    "source": "ID участника, <i>4 байт</i>",
	    "data": "аудио пакет, <i>(size - 8) байт</i>"
    },
    {
      "type": "VIDEO (0x06), <i>1 байт</i>",
	    "source": "ID участника, <i>4 байт</i>",
	    "data": "видео пакет, <i>(size - 8) байт</i>"
    }
  ]
}
@endjson
