@startuml conf-2
skinparam sequenceMessageAlign center
skinparam responseMessageBelowArrow true

title Организация конференции\nдля двух участников

participant "Участник <<А>>" as A
participant "Участник <<Б>>" as B

note left of A
Конференция 1
""conf_id"" = 123
end note
/ note right of B
Конференция 2
""conf_id"" = 456
end note

== Запуск конференции ==

A -> B: <b>""INVITE""
A <-- B: <b>""INVITE_ACCEPT""
note right
""conf_id""
заменяется
с 456 на 123
end note

== Обмен медиа данными ==

opt

loop обмен аудио пакетами 20мс
A ->> B: <b>""AUDIO""
A <<- B: <b>""AUDIO""
end

else

loop обмен видео пакетами 33мс
A ->> B: <b>""VIDEO""
A <<- B: <b>""VIDEO""
end

end

== Завершение конференции ==

alt Завершение участником <<А>>
  A ->> B: <b>""LEAVE""
else Завершение участником <<Б>>
  A <<- B: <b>""LEAVE""
end

@enduml
