#pragma once

#include "version.h"

#define SELECON_DEFAULT_LISTEN_PORT 11235
#define SELECON_DEFAULT_LISTEN_PORT_STR STRINGIFY(SELECON_DEFAULT_LISTEN_PORT)

#define SELECON_DEFAULT_PART_NAME "user0"

#define SELECON_DEFAULT_LISTEN_BUF 5
#define SELECON_DEFAULT_SNDRCV_TIMEOUT 500
