#pragma once

enum SError {
  SELECON_OK = 0,
  SELECON_INVALID_ARG,
  SELECON_INVALID_ADDRESS,
  SELECON_CON_ERROR,
  SELECON_CON_TIMEOUT,
  SELECON_ALREADY_INIT,
  SELECON_EMPTY_CONTEXT,
  SELECON_PTHREAD_ERROR,
};

const char* serror_str(enum SError err);
